# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.SlugField(blank=True, help_text='Leave blank if you want to let the software assign a common name suitable for your subnet', max_length=256, unique=True, verbose_name='cert name')),
                ('ip', models.GenericIPAddressField(blank=True, help_text='Leave blank if you want to let the software assign the first available for your network.', null=True, verbose_name='IP address')),
                ('company', models.CharField(blank=True, max_length=256, null=True, verbose_name='company')),
                ('name', models.CharField(help_text='It should be Name Surname, or hostname. It has to be unique in company', max_length=128, verbose_name='name')),
                ('email', models.EmailField(blank=True, default=b'', max_length=254)),
                ('operating_system', models.CharField(blank=True, choices=[(b'win', 'Windows'), (b'gnu', 'GNU/Linux')], default=None, max_length=32, null=True, verbose_name='operating system')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('cert', models.TextField(blank=True, default=b'', verbose_name='certificate')),
                ('key', models.TextField(blank=True, default=b'', verbose_name='key')),
                ('cert_validity_start', models.DateTimeField(blank=True, null=True)),
                ('cert_validity_end', models.DateTimeField(blank=True, null=True)),
                ('cert_distribution_token', models.CharField(blank=True, max_length=128, null=True)),
                ('cert_distribution_on', models.DateTimeField(blank=True, null=True)),
                ('cert_download_on', models.DateTimeField(blank=True, null=True)),
                ('cert_public_download_on', models.DateTimeField(blank=True, null=True)),
                ('cert_revocation_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('can_access_to', models.ManyToManyField(blank=True, related_name='_client_can_access_to_+', to='base.Client')),
            ],
            options={
                'ordering': ('subnet', 'company', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ClientActionsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('on', models.DateTimeField(auto_now=True)),
                ('remote_ip', models.GenericIPAddressField(default=b'127.0.0.1')),
                ('note', models.TextField(blank=True, default=b'')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Client')),
            ],
            options={
                'ordering': ['-on'],
                'get_latest_by': 'on',
                'verbose_name': 'action log',
            },
        ),
        migrations.CreateModel(
            name='VPNSubnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=31, unique=True, verbose_name='name')),
                ('human_name', models.CharField(max_length=128, unique=True, verbose_name='human name')),
                ('base', models.GenericIPAddressField(unique=True, verbose_name='base')),
                ('bits', models.PositiveSmallIntegerField(verbose_name='bits')),
                ('default_gw', models.GenericIPAddressField(verbose_name='default gateway')),
                ('static_min', models.GenericIPAddressField(verbose_name='first available address')),
                ('static_max', models.GenericIPAddressField(verbose_name='last available address')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('bound_iface', models.CharField(blank=True, max_length=16, verbose_name='bound interface')),
                ('topology', models.CharField(choices=[(b'subnet', b'subnet'), (b'net30', b'net30')], default=b'subnet', max_length=16, verbose_name='topology')),
                ('common_name_template', models.CharField(default=b'%(subnet)s-%(company)s-%(name)s', help_text="Specify a python template string here. Allowed keys are 'name', 'company', 'subnet'", max_length=32, verbose_name='common name template')),
                ('config_server', models.TextField(blank=True, verbose_name='server configuration')),
                ('config_client', models.TextField(blank=True, verbose_name='client configuration')),
            ],
            options={
                'ordering': ['human_name'],
                'abstract': False,
                'verbose_name': 'subnet',
                'verbose_name_plural': 'subnets',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='subnet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.VPNSubnet', verbose_name='Role'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set([('company', 'name', 'enabled'), ('ip', 'enabled')]),
        ),
    ]
